/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCarbonAperture: typeof import('~icons/carbon/aperture')['default']
    IconCarbonIsoOutline: typeof import('~icons/carbon/iso-outline')['default']
    IconLogosVue: typeof import('~icons/logos/vue')['default']
    'IconTabler:cameraSpark': typeof import('~icons/tabler/camera-spark')['default']
    IconTablerAperture: typeof import('~icons/tabler/aperture')['default']
    IconTablerBolt: typeof import('~icons/tabler/bolt')['default']
    IconTablerCalendar: typeof import('~icons/tabler/calendar')['default']
    IconTablerCamera: typeof import('~icons/tabler/camera')['default']
    IconTablerCameraBolt: typeof import('~icons/tabler/camera-bolt')['default']
    IconTablerCameraCog: typeof import('~icons/tabler/camera-cog')['default']
    IconTablerCameraFlash: typeof import('~icons/tabler/camera-flash')['default']
    IconTablerCameraSpark: typeof import('~icons/tabler/camera-spark')['default']
    IconTablerCameraUp: typeof import('~icons/tabler/camera-up')['default']
    IconTablerClock: typeof import('~icons/tabler/clock')['default']
    IconTablerColorFilter: typeof import('~icons/tabler/color-filter')['default']
    IconTablerColorSwatch: typeof import('~icons/tabler/color-swatch')['default']
    IconTablerEyePin: typeof import('~icons/tabler/eye-pin')['default']
    IconTablerEyeTable: typeof import('~icons/tabler/eye-table')['default']
    IconTablerIso: typeof import('~icons/tabler/iso')['default']
    IconTablerRuler: typeof import('~icons/tabler/ruler')['default']
    IconTablerSettings: typeof import('~icons/tabler/settings')['default']
    IconTablerStopwatch: typeof import('~icons/tabler/stopwatch')['default']
    IconTablerSun: typeof import('~icons/tabler/sun')['default']
    IconTablerTemperatureSun: typeof import('~icons/tabler/temperature-sun')['default']
    IconTablerUpload: typeof import('~icons/tabler/upload')['default']
    IconTablerZap: typeof import('~icons/tabler/zap')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
