/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCarbonAperture: typeof import('~icons/carbon/aperture')['default']
    IconLogosVue: typeof import('~icons/logos/vue')['default']
    IconTablerEyeTable: typeof import('~icons/tabler/eye-table')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
