/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCarbonIsoOutline: typeof import('~icons/carbon/iso-outline')['default']
    IconTablerAperture: typeof import('~icons/tabler/aperture')['default']
    IconTablerBolt: typeof import('~icons/tabler/bolt')['default']
    IconTablerCalendar: typeof import('~icons/tabler/calendar')['default']
    IconTablerCamera: typeof import('~icons/tabler/camera')['default']
    IconTablerClock: typeof import('~icons/tabler/clock')['default']
    IconTablerEyePin: typeof import('~icons/tabler/eye-pin')['default']
    IconTablerSettings: typeof import('~icons/tabler/settings')['default']
    IconTablerSun: typeof import('~icons/tabler/sun')['default']
    IconTablerUpload: typeof import('~icons/tabler/upload')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
