/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[imageSlug]': RouteRecordInfo<
      '/[imageSlug]',
      '/:imageSlug',
      { imageSlug: ParamValue<true> },
      { imageSlug: ParamValue<false> },
      | never
    >,
    '/albums/': RouteRecordInfo<
      '/albums/',
      '/albums',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/albums/[albumSlug]': RouteRecordInfo<
      '/albums/[albumSlug]',
      '/albums/:albumSlug',
      { albumSlug: ParamValue<true> },
      { albumSlug: ParamValue<false> },
      | never
    >,
    '/tags/': RouteRecordInfo<
      '/tags/',
      '/tags',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tags/[tag]': RouteRecordInfo<
      '/tags/[tag]',
      '/tags/:tag',
      { tag: ParamValue<true> },
      { tag: ParamValue<false> },
      | never
    >,
    '/upload': RouteRecordInfo<
      '/upload',
      '/upload',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/[imageSlug].vue': {
      routes:
        | '/[imageSlug]'
      views:
        | never
    }
    'src/pages/albums/index.vue': {
      routes:
        | '/albums/'
      views:
        | never
    }
    'src/pages/albums/[albumSlug].vue': {
      routes:
        | '/albums/[albumSlug]'
      views:
        | never
    }
    'src/pages/tags/index.vue': {
      routes:
        | '/tags/'
      views:
        | never
    }
    'src/pages/tags/[tag].vue': {
      routes:
        | '/tags/[tag]'
      views:
        | never
    }
    'src/pages/upload.vue': {
      routes:
        | '/upload'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
